device: cuda:0

loader:
  batch_size: 128
  num_workers: 0
  pin_memory: True

METHOD:
  name: 'LargeLossMatters'
  backbone: 'resnet50'
  freeze_backbone: False
  mod_scheme: 'LL-R'
  delta_rel: 0.5

OPTIMIZER:
  name: 'Adam'
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.0005
  epochs: 2

DATASET:
  name: 'RAP'
  pkl_path: '/home/ayp/dataset/attribute/RAPv1.pkl'

LOGGING:
  logger: 'tensorboard'
  log_dir: './logs'
  model_path: './save'
  load_model: False
  project: 'LargeLossMatters'
  postfix: 'test'