device: cuda:1

loader:
  batch_size: 32
  num_workers: 2
  pin_memory: True
  
METHOD:
  name: 'LargeLossMatters'
  backbone: 'resnet50'
  freeze_backbone: False
  mod_scheme: 'LL-R'
  delta_rel: 0.1

OPTIMIZER:
  name: 'Adam'
  lr: 0.00001
  weight_decay: 0.0001
  epochs: 100

DATASET:
  name: 'rap1'
  pkl_path: '/home/ayp/share_projects/datasets/attribute/rap1_42.pkl'
  use_feature: False
  transforms:
    input_size: 112
    input_ratio: 2.0

LOGGING:
  logger: 'wandb'
  log_dir: './logs'
  model_path: './save'
  load_model: False
  project: 'LargeLossMatters'
  postfix: 'rap_bsz32'